<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>IptvStarterApp</RootNamespace>
    <AssemblyName>IptvStarterApp</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidEnableDesugar>true</AndroidEnableDesugar>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.0.2" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.9.2.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.9.2.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.9.2.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.9.2.1" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.9.2.1" />
    <PackageReference Include="Xamarin.AndroidX.RecyclerView" Version="1.4.0.3" />
    <PackageReference Include="Xamarin.AndroidX.Media3.Exoplayer" Version="1.8.0" />
    <PackageReference Include="Xamarin.AndroidX.Media3.Exoplayer.Hls" Version="1.8.0" />
    <PackageReference Include="Xamarin.AndroidX.Media3.Ui" Version="1.8.0" />
  </ItemGroup>
</Project>
